version: 2
jobs:
  build:
    working_directory: ~/nextcloud
    machine:
      docker_layer_caching: true
    steps:
      - checkout

      - run:
          name: Build Nextcloud image
          command: |
            source ./.circleci/release.sh
            docker build -t fundocker/nextcloud:${CIRCLE_SHA1} \
              --build-arg NEXTCLOUD_VERSION=${NEXTCLOUD_VERSION} \
              .

      - run:
          name: list available images
          command: docker images fundocker/nextcloud

  hub:
    working_directory: ~/nextcloud
    machine:
      docker_layer_caching: true
    steps:
      - checkout

      - run:
          name: Build Nextcloud image
          command: |
            source ./.circleci/release.sh
            docker build -t fundocker/nextcloud:${CIRCLE_SHA1} \
              --build-arg NEXTCLOUD_VERSION=${NEXTCLOUD_VERSION} \
              .

      - run:
          name: list available images
          command: docker images fundocker/nextcloud

      # Login to DockerHub to Publish new images
      #
      # Nota bene: you'll need to define the following secrets environment vars
      # in CircleCI interface:
      #
      #   - DOCKER_USER
      #   - DOCKER_PASS
      - run:
          name: Login to DockerHub
          command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - run:
          name: tag images
          command: |
            source ./.circleci/release.sh
            docker tag fundocker/nextcloud:${CIRCLE_SHA1} fundocker/nextcloud:latest
            docker tag fundocker/nextcloud:${CIRCLE_SHA1} fundocker/nextcloud:${NEXTCLOUD_VERSION}

      - run:
          name: publish images
          command: |
            source ./.circleci/release.sh
            docker push fundocker/nextcloud:latest
            docker push fundocker/nextcloud:${NEXTCLOUD_VERSION}

workflows:
  version: 2
  nextcloud:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - hub:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*-fpm/

